# Generated by Django 3.2.3 on 2021-06-01 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=150)),
                ('excerpt', models.CharField(max_length=500)),
            ],
        ),
    ]
